### ISSUE TITLE
pmpro_requirebilling

### ISSUE THREAD

**Issue by jessicahawkins3344** [strangerstudios/pmpro-add-paypal-express#1]
The radio fields are still showing when the pmpro_requirebilling fitler is false. 

It works in the basic checkout.php when I don't have this enabled.

So, when I use a discount code that brings the total to $0, the "Choose Payment Method" with radio button options are still visible and they shouldn't be.

I've been messing around for a bit, but I can't figure it out.

**Comment by kimcoleman** [comment]
We are not hearing current reports of this old issue. I am going to close this and will resurface if we hear this issue is active.
