### ISSUE TITLE
Cancelling current subscriptions too early

### ISSUE THREAD

**Issue by mjulian87** [strangerstudios/pmpro-add-paypal-express#12]
If a user has an active subscription (paying with Stripe, most likely other gateways but I'm unable to test) and they go to change level, select 'Checkout with Paypal' but fail to complete payment, their Stripe subscription is cancelled regardless of whether the Paypal payment is completed or not.

Should the current subscription not be cancelled after confirmation of the new payment?

This obviously only happens with this plugin, as it requires multiple gateways, but the issue appears to come from the pmpro core code.

**Comment by kimcoleman** [comment]
We are not hearing current reports of this old issue. I am going to close this and will resurface if we hear this issue is active.
