### ISSUE TITLE
BUG: Not displaying correct buttons on checkout if PBC setting is "only check" for level.

### ISSUE THREAD

**Issue by messica** [strangerstudios/pmpro-add-paypal-express#13]
If Pay by Check is activated and .a level's Pay by Check setting is "Yes. Users can only pay by check.", the check instructions are not displayed on the checkout page, but the PayPal option still is.

**Support Ticket (Moderators Only)**
https://www.paidmembershipspro.com/forums/topic/pay-by-check-disappear/

**Comment by kimwhite** [comment]
This is still a problem. I have recreated the issue and the "Pay by Credit Card" option will still appear when making a level "Check Only"

**Comment by kimwhite** [comment]
For a quick fix, hiding the box for check only levels appears to work. https://gist.github.com/kimwhite/67cc6b7b8094a71f6a52a93eab222904
