### ISSUE TITLE
Asterisk next to address fields disappear after clicking on PayPal button

### ISSUE THREAD

**Issue by femiyb** [strangerstudios/pmpro-add-paypal-express#22]
Here’s how to reproduce the problem.
1. Go to the page and click on the radio button for Check Out with PayPal
2. Click on the button all the way at the bottom that says PayPal Check out (The safer, easier way to pay)
3. Click on the radio button that says Check Out with a Credit Card

Now you will see all the asterisks are gone.

Related ticket: https://www.paidmembershipspro.com/forums/topic/asterisk-next-to-address-fields-disappear-after-clicking-on-paypal-button/

**Comment by jeiseman** [comment]
This problem occurs when you have Stripe chosen as the payment gateway and PayPal Express as a secondary option. I have switched to use PayPal standard so I no longer have this problem.
