### ISSUE TITLE
PayPal requires Credit Card

### ISSUE THREAD

**Issue by uno-de-piera** [strangerstudios/pmpro-add-paypal-express#23]
After add pmpro-add-paypal-express plugin and select PayPal for pay the subscription the form requires Stripe form data, any idea?

![image](https://user-images.githubusercontent.com/4218670/72562130-fee15f00-38aa-11ea-8f8a-b45571d9180c.png)

Thanks!

**Comment by andrewlimaza** [comment]
The Add PayPal Express is to add PayPal Express as a second option, so you may offer Stripe (or another gateway) and PayPal Express.

If you need support for this Add On, please reach out on www.paidmembershipspro.com

I hope this is a good starting point.
