### ISSUE TITLE
Invoice email not being sent

### ISSUE THREAD

**Issue by hbcondo** [strangerstudios/pmpro-add-paypal-express#24]
We have Stripe and this PayPal Express add-on for accepting payments on our site. Our members that pay with a credit card via Stripe all receive Invoice emails. However, **all our members that pay with PayPal DO NOT have outgoing Invoice emails sent to them**. 

We also have the Email Templates addon to help manage the emails and the Invoice template is not disabled. 

Can the PMP team please review this asap? We have received multiple disputes from members stating they never received an Invoice email which has resulted in us refunding them.

To help us verify this, we use the WordPress plugin [MailPoet](https://www.mailpoet.com/) and [SendGrid](https://sendgrid.com/docs/for-developers/sending-email/wordpress-plugin/) as our email gateway that logs all outgoing emails from our WordPress site.

**Comment by andrewlimaza** [comment]
Hey @hbcondo please can you open a support ticket on www.paidmembershipspro.com
