### ISSUE TITLE
Payment button not re-enabled (fix included!)

### ISSUE THREAD

**Issue by DigiEggz** [strangerstudios/pmpro-add-paypal-express#26]
When a user submits incorrect payment info with Stripe and the transaction fails, the "Submit" button is re-enabled but the PayPal button is not. This issue occurs when Stripe and PayPal are both allowed as checkout options. 

The button is not enabled because the code found in `stripeResponseHandler()` does not not re-enable image type buttons. The current code is:
```
if (response.error) {
 // re-enable the submit button
jQuery('.pmpro_btn-submit-checkout,.pmpro_btn-submit').removeAttr("disabled");
…
```

This can be fixed by simply adding the image type to the attributes to enable with jQuery:
```
if (response.error) 
{
// re-enable the submit button and PayPal button
jQuery('.pmpro_btn-submit-checkout,.pmpro_btn-submit,input[type="image"]').removeAttr("disabled");
…
```

**Comment by kimcoleman** [comment]
We are not hearing current reports of this old issue. I am going to close this and will resurface if we hear this issue is active.
