### ISSUE TITLE
Should be possible to define which payment method use as default

### ISSUE THREAD

**Issue by mircobabini** [strangerstudios/pmpro-add-paypal-express#28]
To overcome this missing feature I had to manually edit the code.

But there is a weird case:
1. Manually switch to Credit Card (which is not the default option anymore in my case)
2. Use a valid card not enabled for online payments (wise.com virtual cards for testing purposes)
3. Checkout -- page reloads with error "Your card was declined."
4. Now the default payment method is selected and credit card filled data is lost.

**Comment by kimcoleman** [comment]
We plan to support multiple active payment gateways eventually in core PMPro so we will not tackle this as an isolated update to the Add On. We will consider then if we support a "per level" default gateway / payment method.
