### ISSUE TITLE
Add compatibility with PayFast

### ISSUE THREAD

**Issue by mircobabini** [strangerstudios/pmpro-add-paypal-express#29]
When using PayFast and PP Express is selected, there's a not from PayFast which is not going away:

Temporary glue fix: https://gist.github.com/mircobabini/fc2867b3034f3b73fc25d8efef4f0415

Screenshot:
<img width="970" alt="Screenshot 2021-05-27 at 10 31 18" src="https://user-images.githubusercontent.com/636911/119793361-cefe8e80-bed6-11eb-88c3-3b0f21a2cbc5.png">

**Comment by andrewlimaza** [comment]
The reason this isn't supported is PayFast only supports ZAR currency. PayPal doesn't support ZAR, so I don't think we would fully support this until we figure out a multicurrency solution for these type of cases.
