### ISSUE TITLE
Bad card data still goes through

### ISSUE THREAD

**Issue by robeendey** [strangerstudios/pmpro-add-paypal-express#3]
We've had some customers setting up accounts without actually being charged due to what we think is a bug in this add-on. We use the stripe gateway along with this paypal option. Customers will receive the account created email from PMPro but no confirmation of payment. This has happened multiple times and we think it is because users who have out-dated/bad card data in paypal are still able to proceed with checkout. See below for a comment from a user who kindly explained what happens:

"Ok no problem. I just noticed that there was a problem with the card in my paypal account. 
Think there is a glitch when you sign up with paypal and the card information is out of date. Paypal sends an error but only after your website receives an ok so it seems."

**Comment by Vikkia** [comment]
I'm experiencing this issue too with PMPro and PayPal.
Has this been resolved yet?

**Comment by kimcoleman** [comment]
We are not hearing current reports of this old issue. I am going to close this and will resurface if we hear this issue is active.
