### ISSUE TITLE
Use with paypal standard.

### ISSUE THREAD

**Issue by gianght90** [strangerstudios/pmpro-add-paypal-express#39]
Can it work with paypal standard? Some of my customers don't want to register for a paypal account, just want to pay via visa card.

**Comment by kimcoleman** [comment]
This does not work with PayPal Standard - PayPal almost always requires users to have a PayPal account in order to set up a subscription. If you prefer to allow credit card payments, please consider using Stripe as your primary gateway and offering PayPal Express as an option using this Add On.
