### ISSUE TITLE
Causes checkout to freeze

### ISSUE THREAD

**Issue by jemichael** [strangerstudios/pmpro-add-paypal-express#5]
Installed plugin, set Paypal Express email and hit save. Then switched back to Stripe and hit Save. Went to Membership Levels, selected level that took me to checkout. I see two two radios for credit card and for paypal. However, the page is just "loading" and neither radio link works. 

PMPRO: Version 1.8.8.3
Wordpress: 4.4.2

**Comment by Vikkia** [comment]
I'm experiencing this issue too with PMPro and PayPal Express.
Has this been resolved yet?

**Comment by golmon** [comment]
Hello, I have exactly the same problem. Has anyone found a solution since ?

**Comment by kimcoleman** [comment]
We are not hearing current reports of this old issue. I am going to close this and will resurface if we hear this issue is active.
