### ISSUE TITLE
PayPal Express vanished from PMPro Payment Settings page

### ISSUE THREAD

**Issue by moubarat** [strangerstudios/pmpro-add-paypal-express#7]
I had installed “Add PayPal Express as an Alternate Payment Option at Checkout” and it was working fine. But after recent update it vanished. I tried removing the plugin and re-installing but though the plugin is active in plugins list…I don’t see PayPal Express settings in the PMPro Payment Settings page.

**Comment by kimcoleman** [comment]
We are not hearing current reports of this old issue. I am going to close this and will resurface if we hear this issue is active.
